-   id: bazel-buildifier
    name: bazel buildifier
    description: Runs `buildifier`, requires buildifier binary
    entry: buildifier
    files: '^(.*/)?(BUILD\.bazel|BUILD|WORKSPACE)$|\.BUILD$|\.bzl$'
    language: system

-   id: do-not-submit
    name: DO NOT SUBMIT
    description: Forbids the string "DO NOT SUBMIT".
    entry: check_do_not_submit.py
    language: script
    files: '.*'

-   id: clang-format-diff
    name: clang-format-diff
    entry: clang_format.py
    language: script
    args: ['--diff']

    # git-clang-format does not take kindly to being run in parallel; it writes
    # to a speicfic file in .git.
    #
    # TODO: Can we fix git-clang-format so it's parallel-friendly?
    require_serial: true

    # Fun fact, clang-format can format more than just C and C++!
    #
    # Less-fun fact, "types: [c, c++]" means "files that are C *and* C++", i.e.
    # ".h" files.  If you want to clang-format your C and C++ code, AFAICT
    # you'll need separate rules.  Or I guess you can use a "files:" regexp.
    #
    # See README.md for usage examples.

-   id: clang-format-whole-file
    name: clang-format-whole-file
    entry: clang_format.py
    language: script
    args: ['--whole-file']
    require_serial: false
