-   id: bazel-buildifier
    name: bazel buildifier
    description: Runs `buildifier`, requires buildifier binary
    entry: buildifier
    files: '^(.*/)?(BUILD\.bazel|BUILD)$|\.BUILD$' 
    language: system

-   id: do-not-submit
    name: DO NOT SUBMIT
    description: Forbids the string "DO NOT SUBMIT".
    entry: check_do_not_submit.py
    language: script
    files: '.*'

-   id: clang-format
    name: clang-format
    entry: clang_format.py
    language: script

    # Fun fact, clang-format can format more than just C and C++!  By default
    # we only run it on C/C++, but you can override this in your pre-commit
    # config.
    types: [c, c++]
