-   id: bazel-buildifier
    name: 'bazel buildifier'
    description: "Runs `buildifier`, requires buildifier binary"
    entry: buildifier
    files: 'BUILD.bazel|BUILD|WORKSPACE'
    language: 'system'
